# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38a4ade57f4b6828c15087f8c73b80cf15d4cb8ef8eb343dcb054c17468245981cb2b19322a57326573a46edde9216b3e7e9993728ade9b1943c11ed2559bf11

test:
  secret_key_base: 22513fdd34207992e9f0847cb3f7f115f174df7bfd32219777afe20d22cbd17ebc640979c160a406a7be65be301b2bebf28e2deec406f673db0874dbfbce6aa5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
